#!/usr/bin/env bash

SERVICE=$1 # The service name to be bootstrapped, possible values are activemq, ibmmq, rabbitmq
COMPOSE_FILE="compose/docker-compose.yml"

if [ "$SERVICE" = "ibmmq" ];
then
    echo "Shutting down the IBMMQ playbook"
    COMPOSE_FILE="compose/docker-compose-ibmmq.yml"
elif [ "$SERVICE" = "activemq" ];
then
    echo "Shutting down the ActiveMQ playbook"
    COMPOSE_FILE="compose/docker-compose-activemq.yml"

elif [ "$SERVICE" = "rabbitmq" ];
then
    echo "Shutting down the RabbitMQ playbook"
    COMPOSE_FILE="compose/docker-compose-rabbitmq.yml"
else
    echo "Usage(): ./up [activemq | ibmmq | rabbitmq]"
    exit 1
fi


docker-compose -f $COMPOSE_FILE  down
